### ISSUE TITLE
no matches for kind "Ingress" in version "networking.k8s.io/v1"

### ISSUE THREAD

**Issue by dehghanfar** [datalust/helm.datalust.co#7]
installing the chart with ingress as true in the config file

getting this error:
`
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"`

my versions

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"c86ad89b8715ed17fd55b87cbb2888ccc6fa9878", GitTreeState:"clean", BuildDate:"2020-09-25T01:53:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

I believe V1 is only available on v19+ and not on 18. can this be fixed?

**Comment by KodrAus** [comment]
Hi @dehghanfar :wave:

There are some changes in configuration between the stable v1 and beta versions of the ingress API that made it harder for us to support both concurrently. The current policy for the chart has been to update from beta to stable versions as we get the chance, but since these APIs are still actively stabilized and deprecated we might be able to come up with a better one that makes it easier to track what versions each major version of the chart supports.

If you need to continue to run on older API versions your best bet might be to set up your own deployment based on the chart.

**Comment by dehghanfar** [comment]
hello sir, I understand, I updated my cluster to v19, that fixed the problem for now.

**Comment by softlion** [comment]
Don't support old k8s versions, too dangerous given the number of attacks on information systems.

**Comment by nblumhardt** [comment]
Thanks for the note @softlion; sounds like the OP's problem here was resolved with an upgrade, so closing 👍
